apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  namespace: appwork
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/lib/mongo"
    server: 10.221.178.156
    readOnly: false
