apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  namespace: appwork
spec:
  storageClassName: generic
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
