apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwork-web
  namespace: appwork
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appwork-web
  template:
    metadata:
      labels:
        app: appwork-web
    spec:
      containers:
      - name: appwork-web
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/
        image: unitynts/appwork_web
        ports:
        - containerPort: 3000
      restartPolicy: Always
